#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  4 09:22:21 2018


"""

import urllib
import json

url = "https://ephtracking.cdc.gov:443/apigateway/api/v1/getCoreHolder/441/102/ALL/ALL/2016/0/0?PMDisplayId=1,2"
with urllib.request.urlopen(url) as f:
    data=f.read().decode('utf-8')
